#!/bin/bash
# Train latency and length predictors from baseline MAS inference CSV data.
# This script assumes the CSV has already been generated by the inference sweep.

# Blue storage configuration
BLUE_STORAGE="/blue/qi855292.ucf/ah872032.ucf"

# Input CSV (generated by the inference sweep)
INPUT_CSV="logs/generate_data_for_latency_length_predictor/baseline_mas_inference_math_train_519_poisson.csv"

# Output checkpoint directory
SAVE_DIR="${BLUE_STORAGE}/checkpoints/predictors"
mkdir -p "$SAVE_DIR"

# Training hyperparameters
EPOCHS=50
BATCH_SIZE=32
LR=0.001

echo "========================================"
echo "Latency & Length Predictor Training"
echo "Input CSV:  ${INPUT_CSV}"
echo "Save dir:   ${SAVE_DIR}"
echo "Epochs:     ${EPOCHS}"
echo "Batch size: ${BATCH_SIZE}"
echo "LR:         ${LR}"
echo "========================================"
echo ""

python Experiments/train_latency_length_predictor.py \
    --csv "$INPUT_CSV" \
    --record-type step \
    --save-dir "$SAVE_DIR" \
    --epochs "$EPOCHS" \
    --batch-size "$BATCH_SIZE" \
    --lr "$LR"

echo ""
echo "========================================"
echo "Training complete!"
echo "Checkpoints saved to: ${SAVE_DIR}"
ls -lh "${SAVE_DIR}/"*.pth 2>/dev/null || echo "No checkpoints found."
echo "========================================"
